[sdl]
fullscreen=false
output=surface
windowresolution=640x400

[cpu]
cycles=max

[dosbox]
nocachedir=true

[autoexec]
mount c src
mount s ../share
s:
mkdir _MAGIC_
c:
echo About to run DOSMCP.COM...
DOSMCP.COM S:
echo DOSMCP.COM exited
pause
