[sdl]
fullscreen=false
output=surface
windowresolution=640x400

[cpu]
cycles=max

[dosbox]
nocachedir=true

[autoexec]
mount c /Users/derrick/Documents/86box-vms/stars-win311/smb-share/tsr
mount z /Users/derrick/Documents/86box-vms/stars-win311/smb-share/share
z:
mkdir _MAGIC_
c:
echo About to run MCP.COM...
MCP.COM Z:
echo MCP.COM exited
pause
